---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-1
  name: svc-redis-1
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-1
  name: redis-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-1
  template:
    metadata:
      labels:
        app: redis-1
    spec:
      containers:
      - image: redis
        name: redis
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        command: 
          - redis-server
          - "/redis-master/redis.conf"
        args: ["--replica-announce-ip svc-redis-1"]
        volumeMounts:
        - name: "pvc-redis"
          mountPath: "/data"
        - name: config
          mountPath: /redis-master
      volumes:
      - name: "pvc-redis"
        persistentVolumeClaim:
          claimName: "pvc-redis-1"
      - name: "config"
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
---