apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    daemonize no
    pidfile "/var/run/redis/6379.pid"
    dir "/data"
    port 6379
    bind 0.0.0.0
    timeout 0
    tcp-keepalive 0
    tcp-backlog 64534
    logfile "/data/redis.log"
    loglevel notice
    syslog-enabled yes
    syslog-ident "redis_6379"
    syslog-facility user
    databases 128

    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename "dump.rdb"

    # Replication
    replica-serve-stale-data yes
    replica-read-only yes
    repl-disable-tcp-nodelay no
    replica-priority 100
    min-replicas-max-lag 10
    masterauth {{ .Values.securityContext.redisPass }}

    # Security
    requirepass {{ .Values.securityContext.redisPass }}

    # Limits
    maxclients 65504
    maxmemory-policy volatile-lru

    # Append Only Mode
    appendonly no
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Lua
    lua-time-limit 5000

    # Slow Log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Event Notification
    notify-keyspace-events "xE"

    # Advanced
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-entries 512
    list-max-ziplist-value 64
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 1gb 1gb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    aof-rewrite-incremental-fsync yes