---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel-1
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.storage.sentinelStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel-2
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.storage.sentinelStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-sentinel-3
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.storage.sentinelStorage }}